server:
  port: 8600
mqtt:
  hostUrl: tcp://127.0.0.1:1883
  username: admin
  password: public
  client-id: IOT-EPC-FD
  cleanSession: true
  reconnect: true
  keepAlive: 100
  isOpen: true
  qos: 1

spring:
  profiles:
    active: hushi_saihan
    #redis配置
  redis:
    host: 127.0.0.1
    port: 16379
    password:

beanName: hikvisionDevice
