server:
  port: 9600
mqtt:
  hostUrl: tcp://127.0.0.1:1883
  username: admin
  password: wanda@1234
  client-id: IOT-EPC-FD
  cleanSession: true
  reconnect: true
  keepAlive: 100
  isOpen: true
  qos: 1

spring:
  redis:
    host: 127.0.0.1
    port: 16379
    password:

beanName: boschSecurityDeviceSdk
#广场ID及GatewayId
epc:
  gatewayId: FD
  gcId: 4307020030
  subsystem: fdxt/
  rcvAddress: 10.10.49.130|7700
  pCtlAddress: 10.10.49.131|7700
  serviceIp: 10.10.49.61|7700
  threadNum: 1
zhf:
  cron: 0 0/30 * * * ?


