server:
  port: 18800
mqtt:
  hostUrl: tcp://127.0.0.1:1883
  username: admin
  password: wanda@1234
  client-id: IOT-EPC-FD
  cleanSession: true
  reconnect: true
  keepAlive: 100
  isOpen: true
  qos: 1

beanName: deviceHandler
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
#广场ID及GatewayId
epc:
  gatewayId: FD
  gcId: 5001130030
  subsystem: fdxt/
  threadNum: 1
  host: http://192.168.11.2:50014
  appKey: 26194113
  appSecret: gxw4VWg0jF8UmBjalX1U
  cron: 0/30 * * * * ?
  #查询报警主机
  search: /api/resource/v2/iasDevice/search
  #查询防区通道列表
  searchDefence: /api/scpms/v1/iasDevice/defence
  #  控制
  control: /api/scpms/v1/subsystem/status/issue
  #子系统状态
  subSysStatus: /api/scpms/v1/subSys/status
  #  防区状态
  defenceStatus: /api/scpms/v1/defence/status
