server:
  port: 8101
beanName: deviceHandler
mqtt:
  hostUrl: tcp://127.0.0.1:1883
  username: admin
  password: wanda@1234
  client-id: IOT-EPC-FD
  cleanSession: true
  reconnect: true
  keepAlive: 100
  isOpen: true
  qos: 1

spring:
  redis:
    host: 127.0.0.1
    port: 16379
    password:
#广场ID及GatewayId
epc:
  gatewayId: FD
  gcId: 4409021082
  subsystem: fdxt/
  threadNum: 1
  host: https://192.168.1.200
  clientId: maomingmaonan
  clientSecret: 6a8e7ba0-f6bb-47a9-ad55-35f13d68d232
  grantType: password
  username: openApiUser
  password: system12345
  version: 1.0.0
  service: ThirdParty
  localhost: 10.165.176.120
  machineId: 1000085
  cron: 0/30 * * * * ?
