#广场ID及GatewayId
epc:
  gatewayId: FD
  gcId: 3310020020
  subsystem: fdxt/
  threadNum: 5
mqtt:
  hostUrl: tcp://127.0.0.1:1883
hikVision:
  ip: 192.168.18.9
  port: 8000
  user: admin
  pwd: qzwd1234
