#广场ID及GatewayId
epc:
  gatewayId: FD
  gcId: 1501050050
  subsystem: fdxt/
  threadNum: 10

#防盗报警串口相关配置
host: 192.168.10.253:443
appKey: 23710630
appSecret: DJEs5iMZ58Tk3FBdOItu
type: application/json
artemisPath: /artemis
#查询入侵报警主机通道列表v2
iasChannelUrl: /api/resource/v2/iasChannel/search
#查询防区状态
defenceUrl: /api/scpms/v1/defence/status
#子系统布撤防
subsystemUrl: /api/scpms/v1/subsystem/status/issue
# 查询子系统状态
subSysStatusUrl: /api/scpms/v1/subSys/status
