package com.dh.DpsdkCore;

public interface fDPSDKGetAreaSpeedDetectCallback {
    public void invoke(int nPDLLHandle,
                       byte[] szAreaId,
                       byte[] szAreaName,
                       byte[] szStartDevId,
                       int nStartChnNum,
                       byte[] szStartChnId,
                       byte[] szStartDevName,
                       byte[] szStartDevChnName,
                       long nStartCapTime,
                       int nStartCarSpeed,
                       byte[] szStartPosId,
                       byte[] szStartPosName,
                       byte[] szEndDevId,
                       int nEndChnNum,
                       byte[] szEndChnId,
                       byte[] szEndDevName,
                       byte[] szEndDevChnName,
                       long nEndCapTime,
                       int nEndCarSpeed,
                       byte[] szEndPosId,
                       byte[] szEndPosName,
                       int nAreaRange,
                       int nMinSpeed,
                       int nMaxSpeed,
                       byte[] szCarNum,
                       int nCarNumType,
                       int nCarNumColor,
                       int nCarColor,
                       int nCarType,
                       int nCarLogo,
                       int nCarAvgSpeed,
                       int nIsIllegalSpeed,
                       int nPicNum,
                       byte[] szPicName0,
                       byte[] szPicName1,
                       byte[] szPicName2,
                       byte[] szPicName3,
                       byte[] szPicName4,
                       byte[] szPicName5,
                       int nRtPlateleft,
                       int nRtPlatetop,
                       int nRtPlateright,
                       int nRtPlatebottom,
                       byte[] szCarPlatePicURL);
}
