package com.dh.DpsdkCore;

public interface fDPSDKTrafficAlarmCallback {
    public void invoke(int nPDLLHandle,
                       byte[] szCameraId,
                       byte[] nPtsIp,
                       byte[] nPtsIpy,
                       int nPicPort,
                       int nPicPorty,
                       int type,
                       byte[] szCarNum,
                       int nLicentype,
                       int nCarColor,
                       int nCarLogo,
                       int nWay,
                       byte[] szPicUrl0,
                       byte[] szPicUrl1,
                       byte[] szPicUrl2,
                       byte[] szPicUrl3,
                       byte[] szPicUrl4,
                       byte[] szPicUrl5,
                       int nPicGroupStoreID,
                       int bNeedStore,
                       int bStored,
                       int nAlarmLevel,
                       int nAlarmTime,
                       int nChannel,
                       byte[] szDeviceId,
                       byte[] szDeviceName,
                       byte[] szDeviceChnName,
                       int nCarType,
                       int nCarSpeed,
                       int nCarLen,
                       int nCardirect,
                       int nMaxSpeed,
                       int nMinSpeed,
                       int nRtPlateleft,
                       int nRtPlatetop,
                       int nRtPlateright,
                       int nRtPlatebottom,
                       byte[] szMessage);
}
